######################################################################
# Automatically generated by qmake (3.0) ?? ??? 20 19:29:22 2015
######################################################################

TEMPLATE = app
TARGET = gotocell1
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
